# Visualize Fiction 配置文件

# 系统配置
system:
  working_dir: "./workspace"
  temp_dir: "./temp"
  output_dir: "./output"
  log_level: "info"
  max_concurrent_tasks: 4
  cache_enabled: true
  cache_size_limit: "5GB"

# 文本预处理模块配置
text_processing:
  # 章节解析器配置
  chapter_parser:
    # 文件读取配置
    file_reader:
      encodings: 
        - utf-8
        - gbk
        - gb2312
    
    # 章节识别配置
    chapter_detector:
      patterns:
        - '第\s*[一二三四五六七八九十百千万\d]+\s*[章节回].*?\n'
        - '序\s*章.*?\n'
        - '尾\s*声.*?\n'
        - '后\s*记.*?\n'
      min_chapter_length: 100  # 最小章节长度（字符数）
    
    # 存储配置
    storage:
      output_dir: "data/processed/"
      split_chapters: false  # 是否分章节存储

  # 角色信息提取器配置
  character_extractor:
    # LLM配置
    llm:
      model: "deepseek-chat"
      api_key_file: "API.config.yaml"
      max_tokens: 4000
      temperature: 0.7
      retry_count: 3
      timeout: 30
    
    # 提取配置
    extraction:
      batch_size: 5
      max_relevant_chapters: 10
      importance_threshold:
        main: 0.8
        supporting: 0.5
    
    # 特征标准化配置
    feature_standardization:
      enabled: true
      mode: "all"  # all, main, missing
    
    # 输出配置
    output_dir: "data/characters/"
    save_results: true
    
    # 提示模板配置（可选，默认使用内置模板）
    prompts:
      character_extraction: {}
      feature_extraction: {}
      feature_standardization: {}
      

# 肖像生成模块配置
portrait_generation:
  model: "stable-diffusion-xl"
  api_key: "${SD_API_KEY}"
  resolution: "1024x1024"
  steps: 30
  cfg_scale: 7.0
  batch_size: 4
  ip_adapter:
    enabled: true
    weight: 0.8
  controlnet:
    enabled: false
    model: "canny"
    weight: 0.6

# 音频处理模块配置
audio_processing:
  tts_engine: "azure"
  api_key: "${AZURE_TTS_KEY}"
  default_voice: "zh-CN-XiaoxiaoNeural"
  format: "mp3"
  sample_rate: 24000
  character_voices:
    "protagonist": "zh-CN-YunxiNeural"
    "antagonist": "zh-CN-YunjianNeural"
    "narrator": "zh-CN-YunyangNeural"
  audio_effects:
    normalization: true
    noise_reduction: true

# 视频合成模块配置
video_synthesis:
  resolution: "1920x1080"
  fps: 30
  codec: "h264"
  bitrate: "5M"
  animation:
    type: "ken_burns"
    duration: 5.0
    transition: "fade"
  subtitles:
    enabled: true
    font: "SimHei"
    size: 24
    color: "#FFFFFF"
    outline: true

# 角色微调工具配置
character_tuner:
  # LLM配置
  llm:
    model: "deepseek-chat"
    api_key_file: "API.config.yaml"
    max_tokens: 4000
    temperature: 0.7
    retry_count: 3
    timeout: 30
    json_mode: true
  
  # 微调配置
  tuning:
    history_size: 10  # 历史记录大小
    auto_validate: true  # 自动验证特征
    default_style: "realistic"  # 默认风格
    
  # 输出配置
  output:
    dir: "data/characters/"  # 输出目录
    backup: true  # 是否备份原始文件
    format: "json"  # 输出格式（json/yaml）
    indent: 2  # 缩进空格数
    
  # 提示模板配置（可选，默认使用内置模板）
  prompts:
    feature_edit: {}  # 特征编辑提示模板
    feature_regenerate: {}  # 特征重新生成提示模板
    batch_edit: {}  # 批量编辑提示模板
